[package]
name = "diegruft"
version = "0.1.0"
edition = "2021"
authors = ["Max Gilmour"]
readme = "README.md"
repository = "https://github.com/maxgmr/pacbrow"
license-file = "LICENSE"

[dependencies]

[dev-dependencies]
pretty_assertions = "1"
