[package]
name = "dgruft"
version = "0.1.0"
edition = "2021"
authors = ["Max Gilmour"]
readme = "README.md"
repository = "https://github.com/maxgmr/dgruft"
license-file = "LICENSE"

[dependencies]
sha2 = "0.10"

[dev-dependencies]
pretty_assertions = "1.4"
