[package]
name = "dgruft"
version = "0.1.4"
edition = "2021"
authors = ["Max Gilmour"]
readme = "README.md"
repository = "https://github.com/maxgmr/dgruft"
license-file = "LICENSE"

[dependencies]
rand = "0.8.5"
sha2 = "0.10"
base64ct = { version = "1.6", features = ["alloc"] }
rusqlite = { version = "0.31", features = ["bundled"] }
regex = "1.10"

[dev-dependencies]
pretty_assertions = "1.4"
hex-literal = "0.4"

[features]
default = ["frontend"]
frontend = []
