[package]
name = "dgruft"
version = "0.2.0"
edition = "2021"
authors = ["Max Gilmour"]
readme = "README.md"
repository = "https://github.com/maxgmr/dgruft"
license-file = "LICENSE"

[dependencies]
aes-gcm = "0.10"
base64ct = { version = "1.6", features = ["alloc"] }
pbkdf2 = "0.12"
rand_chacha = "0.3"
regex = "1.10"
rusqlite = { version = "0.31", features = ["bundled"] }
sha2 = "0.10"

[dev-dependencies]
pretty_assertions = "1.4"
hex-literal = "0.4"

[features]
default = ["frontend"]
frontend = []
